## mybatis
mybatis:
  mapper-locations: classpath*:com/phy/ebuy/dao/mapping/*.xml
  typeAliasesPackage: com.phy.ebuy.model

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pxlibrary?serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    db-name: pxlibrary
    filters: log4j,wall,mergeStat
    driverClassName: com.mysql.cj.jdbc.Driver