server:
  port: 8008
## mybatis
mybatis:
  mapper-locations: classpath*:com/phy/pxlibrary/dao/mapping/*.xml
  typeAliasesPackage: com.phy.pxlibrary.model
# 打印sql
logging:
  level:
    com.phy.pxlibrary.dao : debug
spring:
  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/pxsdn?serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf8
    url: jdbc:mysql://123.57.22.91:3306/pxsdn?serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    db-name: pxlibrary
    filters: log4j,wall,mergeStat
    driverClassName: com.mysql.cj.jdbc.Driver
